# ISO3 -> deutscher Landesname, exakt die Laenderliste des GWIS-Scopes "gwis"
# (uebernommen aus der Live-API von effis.emergency.copernicus.eu, siehe precompute.py).
COUNTRIES_DE = {
    "ALB": "Albanien",
    "AND": "Andorra",
    "AUT": "Österreich",
    "BLR": "Belarus",
    "BEL": "Belgien",
    "BIH": "Bosnien und Herzegowina",
    "BGR": "Bulgarien",
    "HRV": "Kroatien",
    "CYP": "Zypern",
    "CZE": "Tschechien",
    "DNK": "Dänemark",
    "EST": "Estland",
    "FRO": "Färöer",
    "FIN": "Finnland",
    "FRA": "Frankreich",
    "DEU": "Deutschland",
    "GIB": "Gibraltar",
    "GRC": "Griechenland",
    "GGY": "Guernsey",
    "HUN": "Ungarn",
    "ISL": "Island",
    "IRL": "Irland",
    "IMN": "Isle of Man",
    "ITA": "Italien",
    "JEY": "Jersey",
    "XKO": "Kosovo",
    "LVA": "Lettland",
    "LIE": "Liechtenstein",
    "LTU": "Litauen",
    "LUX": "Luxemburg",
    "MLT": "Malta",
    "MDA": "Moldau",
    "MCO": "Monaco",
    "MNE": "Montenegro",
    "NLD": "Niederlande",
    "MKD": "Nordmazedonien",
    "NOR": "Norwegen",
    "POL": "Polen",
    "PRT": "Portugal",
    "ROU": "Rumänien",
    "RUS": "Russland",
    "SMR": "San Marino",
    "SRB": "Serbien",
    "SVK": "Slowakei",
    "SVN": "Slowenien",
    "ESP": "Spanien",
    "SJM": "Svalbard und Jan Mayen",
    "SWE": "Schweden",
    "CHE": "Schweiz",
    "UKR": "Ukraine",
    "GBR": "Vereinigtes Königreich",
    "VAT": "Vatikanstadt",
    "ALA": "Åland",
}
